security:  
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext    

    role_hierarchy:
        ROLE_ADMIN:         ROLE_USER

    providers:
        chain_provider:
              chain:
                  providers: [fos_userbundle]
        fos_userbundle:
            id: fos_user.user_provider.username

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api_login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
        api_register:
            pattern:  ^/api/register
            stateless: true
            anonymous: true
        api:
              pattern: ^/api
              stateless: true
              anonymous: false
              provider: chain_provider
              guard:
                  authenticators:
                      - lexik_jwt_authentication.jwt_token_authenticator